"""
CSV import/export functionality
"""
import csv
from pathlib import Path
from salespipe.models import Lead, Opportunity


class CSVHandler:
    """Handles CSV import and export operations"""

    @staticmethod
    def export_leads_to_csv(leads, filename="leads_export.csv"):
        """Export leads to CSV file"""
        if not leads:
            print("No leads to export")
            return

        with open(filename, 'w', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=[
                'lead_id', 'name', 'email', 'phone', 'source', 'status',
                'location', 'industry', 'company_size', 'created_at'
            ])
            writer.writeheader()

            for lead in leads:
                if isinstance(lead, tuple):
                    # From database query (now has 10 fields)
                    writer.writerow({
                        'lead_id': lead[0],
                        'name': lead[1],
                        'email': lead[2],
                        'phone': lead[3],
                        'source': lead[4],
                        'status': lead[5],
                        'location': lead[6],
                        'industry': lead[7],
                        'company_size': lead[8],
                        'created_at': lead[9]
                    })
                else:
                    # From Lead object
                    writer.writerow(lead.to_dict())

        print(f"Exported {len(leads)} leads to {filename}")

    @staticmethod
    def import_leads_from_csv(filename):
        """Import leads from CSV file"""
        leads = []

        if not Path(filename).exists():
            print(f"File {filename} not found")
            return leads

        with open(filename, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)

            for row in reader:
                lead = Lead(
                    lead_id=None,  # Will be auto-generated by database
                    name=row['name'],
                    email=row['email'],
                    phone=row.get('phone', ''),
                    source=row.get('source', 'import'),
                    status=row.get('status', 'new'),
                    location=row.get('location'),
                    industry=row.get('industry'),
                    company_size=row.get('company_size'),
                    created_at=row.get('created_at')
                )
                leads.append(lead)

        print(f"Imported {len(leads)} leads from {filename}")
        return leads